spring:
  application:
    name: heima-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    openai:
      api-key: sk-33e4ffbf84924ecf9f2942f4e08b29de
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        model: qwen-plus
        completions-path: /v1/chat/completions

  datasource:
    url: jdbc:mysql://localhost:3306/test_ai?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.ai: debug
    com.hxq.ai: debug