---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hexiongqi.
--- DateTime: 2026/4/29 15:38
---

local stock_key = KEYS[1]
local selected_key = KEYS[2]
local waiting_key = KEYS[3]
local course_id = ARGV[1]
local user_id = ARGV[2]
local timestamp = ARGV[3]

local selected = redis.call('SISMEMBER', selected_key, course_id)
if selected == 1 then
    return -2
end

local stock = tonumber(redis.call('GET', stock_key) or "0")
if stock <= 0 then
    redis.call('ZADD', waiting_key, timestamp, user_id)
    return -1
end

redis.call('DECR', stock_key)
redis.call('SADD', selected_key, course_id)
return 1